spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cucp?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: cucp
    password: Cucp_2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
      validation-timeout: 1000
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway-settings:
    url: jdbc:mysql://127.0.0.1:3306/cucp?autoReconnectForPools=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    user: cucp
    password: Cucp_2020
    baseline-on-migrate: true
    baseline-version: 0.0.0
    baseline-description: Initial
  messages:
    basename: i18n/messages
    encoding: UTF-8

  server:
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 2048

#  settings:
#    app:
#      url: cucp://
#    web:
#      url: http://34.105.107.123

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org:
      hibernate:
        SQL: ERROR
        type.descriptor.sql.BasicBinder: ERROR
    http.wire-log: ERROR
  file: logs/application.log
