version: "3.3"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./logs/mysql:/var/log/mysql
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=cucp"
      - "MYSQL_USER=cucp"
      - "MYSQL_PASSWORD=cucp"
      - "MYSQL_ROOT_PASSWORD=Root_2020"
    ports:
      - "33062:3306"
    networks:
      cucp_net:
        ipv4_address: 172.30.0.101
  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - "63792:6379"
    networks:
      cucp_net:
        ipv4_address: 172.30.0.102
  # zipkin:
  #   #   container_name: zipkin
  #     #   image: openzipkin/zipkin-slim
  #       #   ports:
  #         #     - "9411:9411"
  #           #   networks:
  #             #     cucp_net:
  #               #       ipv4_address: 172.30.0.103
volumes:
  dbdata:
networks:
  cucp_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24